-- Auto-generated price updates from invoice analysis
-- Formula: Cost + 8% delivery + ₹18 packaging + category margin
-- Generated by scripts/generate-price-sql.py
-- Run in Supabase SQL editor

-- First add cost_price column if not exists:
ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_price NUMERIC(10,2);

-- ═══════════════════════════════════════════════════════
-- PRICE UPDATES (matched by name similarity ≥35%)
-- ═══════════════════════════════════════════════════════

-- ABSOLUT REPAIR SHAMPOO 300ML
-- Cost:₹509 → Sale:₹699 (was ₹750.0) | Profit:₹132 (25.8%) | 12.1% OFF MRP | Match:67% ↓
UPDATE products SET
  price = 699,
  mrp = 795,
  discount = 12.1,
  cost_price = 508.8
WHERE id = 'd78b1d25-954d-41bb-a5a0-dc656ea23417';

-- PILGRIM ANTI HAIRFALL SERUM 30ML
-- Cost:₹272 → Sale:₹399 (was ₹349.0) | Profit:₹87 (31.9%) | 19.4% OFF MRP | Match:62% ↑
UPDATE products SET
  price = 399,
  mrp = 495,
  discount = 19.4,
  cost_price = 272.25
WHERE id = '0be592d2-c7ce-411a-acb2-ce8ed397ebb5';

-- ABSOLUT REPAIR MASK 250ML
-- Cost:₹639 → Sale:₹849 (was ₹1450.0) | Profit:₹140 (22.0%) | 15.0% OFF MRP | Match:57% ↓
UPDATE products SET
  price = 849,
  mrp = 999,
  discount = 15.0,
  cost_price = 639.36
WHERE id = '3e94af04-7de7-4067-bb85-bc6be258b235';

-- STREAX CANVO HAIR STRAIGHT INTENSE 80G
-- Cost:₹186 → Sale:₹299 (was ₹295.0) | Profit:₹81 (43.4%) | 6.6% OFF MRP | Match:50% ↑
UPDATE products SET
  price = 299,
  mrp = 320,
  discount = 6.6,
  cost_price = 185.6
WHERE id = '864b1f9c-3d3e-4ad6-bbc6-523120477165';

-- STREAX GOLD SERUM 25ML
-- Cost:₹48 → Sale:₹69 (was ₹145.0) | Profit:₹-0 (-0.9%) | 1.4% OFF MRP | Match:50% ↓
UPDATE products SET
  price = 69,
  mrp = 70,
  discount = 1.4,
  cost_price = 47.6
WHERE id = '5104b999-d131-4907-b6c4-3acab0b59f0f';

-- METAL DX SHAMPOO 250ML
-- Cost:₹890 → Sale:₹1199 (was ₹1250.0) | Profit:₹220 (24.8%) | 13.7% OFF MRP | Match:50% ↓
UPDATE products SET
  price = 1199,
  mrp = 1390,
  discount = 13.7,
  cost_price = 889.6
WHERE id = 'fb350c1d-3734-46e4-b2d8-b485a3923616';

-- LISS UNLIMITED SERUM 125ML
-- Cost:₹768 → Sale:₹1099 (was ₹650.0) | Profit:₹252 (32.8%) | 8.4% OFF MRP | Match:50% ↑
UPDATE products SET
  price = 1099,
  mrp = 1200,
  discount = 8.4,
  cost_price = 768.0
WHERE id = 'eedf368f-1313-4980-862f-25d1b079190d';

-- STREAX GLOSS SERUM 45ML
-- Cost:₹99 → Sale:₹154 (was ₹295.0) | Profit:₹29 (29.1%) | 0.6% OFF MRP | Match:50% ↓
UPDATE products SET
  price = 154,
  mrp = 155,
  discount = 0.6,
  cost_price = 99.2
WHERE id = '425ef342-7e57-4d5b-a296-46c1ce72446b';

-- PLIX ROSEMARY ANTI HAIRFALL SHAMPOO 200ML
-- Cost:₹178 → Sale:₹299 (was ₹395.0) | Profit:₹89 (50.3%) | 15.8% OFF MRP | Match:50% ↓
UPDATE products SET
  price = 299,
  mrp = 355,
  discount = 15.8,
  cost_price = 177.5
WHERE id = '8de6e3a3-b224-44fc-9ef6-e287e326bdfd';

-- PILGRIM HAIR GROWTH SERUM 50ML
-- Cost:₹547 → Sale:₹799 (was ₹1299.0) | Profit:₹190 (34.7%) | 19.7% OFF MRP | Match:50% ↓
UPDATE products SET
  price = 799,
  mrp = 995,
  discount = 19.7,
  cost_price = 547.25
WHERE id = 'bbe0ae37-5978-4f0e-a4c6-83cdaa561c48';

-- PILGRIM 2% KOJIC ACID FACE SERUM 30ML
-- Cost:₹272 → Sale:₹399 (was ₹399.0) | Profit:₹87 (31.9%) | 19.4% OFF MRP | Match:43% =
UPDATE products SET
  price = 399,
  mrp = 495,
  discount = 19.4,
  cost_price = 272.25
WHERE id = '823c97a8-e502-48cb-8f41-5538da7df451';

-- IK 3 IN 1 EXPRESS STYLER
-- Cost:₹1910 → Sale:₹2549 (was ₹299.0) | Profit:₹469 (24.5%) | 23.9% OFF MRP | Match:40% ↑
UPDATE products SET
  price = 2549,
  mrp = 3350,
  discount = 23.9,
  cost_price = 1909.5
WHERE id = '762673f2-5b45-478e-87c5-e538fe01a76c';

-- XTENSO CARE SULFATE FREE SHAMPOO 250ML
-- Cost:₹669 → Sale:₹899 (was ₹1450.0) | Profit:₹159 (23.7%) | 14.0% OFF MRP | Match:40% ↓
UPDATE products SET
  price = 899,
  mrp = 1045,
  discount = 14.0,
  cost_price = 668.8
WHERE id = 'cfff7e62-c892-4451-8331-3ce0359e2be7';

-- ABSOLUT REPAIR OIL 90ML
-- Cost:₹890 → Sale:₹1199 (was ₹750.0) | Profit:₹220 (24.8%) | 13.7% OFF MRP | Match:38% ↑
UPDATE products SET
  price = 1199,
  mrp = 1390,
  discount = 13.7,
  cost_price = 889.6
WHERE id = '39925908-d6b4-4370-91ec-bb6dbedc55f0';

-- PILGRIM ROSEMARY WATER 200ML
-- Cost:₹190 → Sale:₹299 (was ₹299.0) | Profit:₹76 (40.1%) | 13.3% OFF MRP | Match:38% =
UPDATE products SET
  price = 299,
  mrp = 345,
  discount = 13.3,
  cost_price = 189.75
WHERE id = '69d1d1b9-a731-4738-92f6-495410e27404';

-- PILGRIM OIL BALANCE GEL FACE WASH 100ML
-- Cost:₹138 → Sale:₹249 (was ₹275.0) | Profit:₹82 (60.0%) | 0.4% OFF MRP | Match:38% ↓
UPDATE products SET
  price = 249,
  mrp = 250,
  discount = 0.4,
  cost_price = 137.5
WHERE id = 'b7858e40-470b-4cbe-a89f-88289b7c3074';

-- PILGRIM 15% VITAMIN C FACE SERUM 20ML
-- Cost:₹327 → Sale:₹499 (was ₹45.0) | Profit:₹128 (39.0%) | 16.1% OFF MRP | Match:38% ↑
UPDATE products SET
  price = 499,
  mrp = 595,
  discount = 16.1,
  cost_price = 327.25
WHERE id = '4f941d56-8b17-4e12-b530-4e3cefb84866';

-- BIGEN HAIR COLOUR 102 40G
-- Cost:₹364 → Sale:₹498 (was ₹1150.0) | Profit:₹87 (23.8%) | 0.2% OFF MRP | Match:33% ↓
UPDATE products SET
  price = 498,
  mrp = 499,
  discount = 0.2,
  cost_price = 364.27
WHERE id = 'b2713055-8189-45a6-833d-835e9163b409';

-- PILGRIM HYDRA GLOW FACE WASH 100ML
-- Cost:₹135 → Sale:₹244 (was ₹145.0) | Profit:₹80 (59.7%) | 0.4% OFF MRP | Match:33% ↑
UPDATE products SET
  price = 244,
  mrp = 245,
  discount = 0.4,
  cost_price = 134.75
WHERE id = '6774c19b-52ce-4d4e-a516-e4028b280279';

-- O3+ BRIDAL OXYGENATING FACIAL KIT
-- Cost:₹473 → Sale:₹699 (was ₹299.0) | Profit:₹170 (35.9%) | 15.8% OFF MRP | Match:33% ↑
UPDATE products SET
  price = 699,
  mrp = 830,
  discount = 15.8,
  cost_price = 473.1
WHERE id = '25deebee-fe36-4a1f-bcb6-f0f89acd4032';

-- LISS UNLIMITED MASK 490G
-- Cost:₹1204 → Sale:₹1599 (was ₹2250.0) | Profit:₹280 (23.3%) | 3.1% OFF MRP | Match:30% ↓
UPDATE products SET
  price = 1599,
  mrp = 1650,
  discount = 3.1,
  cost_price = 1204.5
WHERE id = 'df2a4af5-e4d4-4b34-8663-d83bc2c9dd2e';

-- OSIS SPARKLER SPRAY 300ML
-- Cost:₹650 → Sale:₹899 (was ₹499.0) | Profit:₹179 (27.5%) | 28.1% OFF MRP | Match:30% ↑
UPDATE products SET
  price = 899,
  mrp = 1250,
  discount = 28.1,
  cost_price = 650.0
WHERE id = '7c095e77-fae9-42c2-98db-7fc6b60d65d2';

-- CETAPHIL MOISTURISING LOTION 100ML
-- Cost:₹473 → Sale:₹699 (was ₹295.0) | Profit:₹170 (35.9%) | 11.4% OFF MRP | Match:29% ↑
UPDATE products SET
  price = 699,
  mrp = 789,
  discount = 11.4,
  cost_price = 473.4
WHERE id = 'c7437a7a-0058-44e4-a979-b12cfc8b01dd';

-- MATRIX SOCOLOR 5.5 90GM
-- Cost:₹328 → Sale:₹414 (was ₹550.0) | Profit:₹42 (12.8%) | 0.2% OFF MRP | Match:29% ↓
UPDATE products SET
  price = 414,
  mrp = 415,
  discount = 0.2,
  cost_price = 327.85
WHERE id = '73a60a03-bcf3-455f-88d1-57f22f934269';

-- BBLUNT COLOR 4.31 50GM
-- Cost:₹219 → Sale:₹349 (was ₹399.0) | Profit:₹94 (42.8%) | 12.5% OFF MRP | Match:29% ↓
UPDATE products SET
  price = 349,
  mrp = 399,
  discount = 12.5,
  cost_price = 219.45
WHERE id = '9583a5ba-9165-44bf-946b-b1a18da9ebb1';

-- LUXLISS DAILY CARE CONDITIONER 200ML
-- Cost:₹648 → Sale:₹899 (was ₹1150.0) | Profit:₹182 (28.1%) | 33.4% OFF MRP | Match:29% ↓
UPDATE products SET
  price = 899,
  mrp = 1349,
  discount = 33.4,
  cost_price = 647.52
WHERE id = '72f6478c-6f49-4792-bfa9-02eb59525bae';

-- DERMA CO OIL FREE FACE WASH 100ML
-- Cost:₹151 → Sale:₹249 (was ₹180.0) | Profit:₹68 (44.7%) | 9.5% OFF MRP | Match:29% ↑
UPDATE products SET
  price = 249,
  mrp = 275,
  discount = 9.5,
  cost_price = 151.25
WHERE id = '2952e9fc-7f92-4d4e-8f27-1d8f306d28d5';

-- DERMA CO HYALURONIC AQUA GEL SPF 50G
-- Cost:₹274 → Sale:₹399 (was ₹99.0) | Profit:₹85 (30.8%) | 20.0% OFF MRP | Match:29% ↑
UPDATE products SET
  price = 399,
  mrp = 499,
  discount = 20.0,
  cost_price = 274.45
WHERE id = '52ea917b-a41a-43ab-b5da-3977c122a604';

-- BERINA HAIR SPA CREAM 500GM
-- Cost:₹586 → Sale:₹799 (was ₹55.0) | Profit:₹149 (25.4%) | 12.7% OFF MRP | Match:25% ↑
UPDATE products SET
  price = 799,
  mrp = 915,
  discount = 12.7,
  cost_price = 585.6
WHERE id = 'c689bcc0-1e7f-47a8-bbdc-69786f6f41a6';

-- MINIMALIST RETINOL EYE CREAM
-- Cost:₹329 → Sale:₹498 (was ₹299.0) | Profit:₹124 (37.7%) | 0.2% OFF MRP | Match:25% ↑
UPDATE products SET
  price = 498,
  mrp = 499,
  discount = 0.2,
  cost_price = 329.34
WHERE id = '8b2d4a4b-5789-44fd-8d0e-602e1df69908';


-- ═══════════════════════════════════════════════════════
-- SUMMARY: 30 products updated
-- Expected total profit per sell-through: ₹4148
-- Average margin: ~28.9%
-- ═══════════════════════════════════════════════════════

-- UNMATCHED PRODUCTS (set manually in Price Manager):
-- ❌ IK HAIR DRYER PRO 2500 → Cost:₹3990, Suggested Sale:₹5149, Profit:₹822
-- ❌ BERINA HEAT PROTECTOR 100ML → Cost:₹319, Suggested Sale:₹449, Profit:₹86
-- ❌ TOUCH UP MASCARA → Cost:₹295, Suggested Sale:₹354, Profit:₹17
-- ❌ ENZO SPRAY 420ML → Cost:₹85, Suggested Sale:₹102, Profit:₹-8
-- ❌ XTENSO CARE SULFATE FREE MASK 196GM → Cost:₹826, Suggested Sale:₹1099, Profit:₹189
-- ❌ XTENSO CARE MASK 490GM → Cost:₹1204, Suggested Sale:₹1599, Profit:₹280
-- ❌ O3+ PEEL OFF WHITE CHOCOLATE WAX 165G → Cost:₹240, Suggested Sale:₹349, Profit:₹71
-- ❌ CETAPHIL GENTLE SKIN CLEANSER 125ML → Cost:₹275, Suggested Sale:₹399, Profit:₹84
-- ❌ CETAPHIL OILY SKIN CLEANSER 125ML → Cost:₹449, Suggested Sale:₹649, Profit:₹146
-- ❌ CETAPHIL MOISTURISING CREAM 80G → Cost:₹401, Suggested Sale:₹599, Profit:₹147
-- ❌ RAAGA WAX WHITE CHOCOLATE 800ML → Cost:₹680, Suggested Sale:₹999, Profit:₹247
-- ❌ CETAPHIL DAM LOTION 100G → Cost:₹459, Suggested Sale:₹649, Profit:₹135
-- ❌ CETAPHIL DAM ADV LOTION 30GM → Cost:₹299, Suggested Sale:₹449, Profit:₹108
-- ❌ RICA WHITE CHOCOLATE WAX 800ML → Cost:₹945, Suggested Sale:₹1349, Profit:₹310
-- ❌ RICA DARK CHOCOLATE WAX 800ML → Cost:₹1049, Suggested Sale:₹1498, Profit:₹347
-- ❌ RAAGA PEDI MANICURE CHOCOLATE 63G → Cost:₹145, Suggested Sale:₹249, Profit:₹74
-- ❌ BC TAF 5 SPRAY → Cost:₹260, Suggested Sale:₹312, Profit:₹13
-- ❌ AROMA PEARL KIT → Cost:₹725, Suggested Sale:₹1049, Profit:₹248
-- ❌ OSIS BOUNTY BALM 150ML → Cost:₹806, Suggested Sale:₹1099, Profit:₹211
-- ❌ BC HAIR SPA ENRICH 500ML → Cost:₹409, Suggested Sale:₹549, Profit:₹89
-- ❌ WP BLONDOR MULTI POWER 400GM → Cost:₹798, Suggested Sale:₹1099, Profit:₹220
-- ❌ WP FUSION MASK 150ML → Cost:₹702, Suggested Sale:₹949, Profit:₹173
-- ❌ WP ELEMENTS MASK 150ML → Cost:₹728, Suggested Sale:₹999, Profit:₹195
-- ❌ WP INVIGO ENRICH MASK 150ML → Cost:₹468, Suggested Sale:₹649, Profit:₹126
-- ❌ IK CRIMPER CRIMP AND STYLE → Cost:₹2280, Suggested Sale:₹2949, Profit:₹469
-- ❌ IK PRO TITANIUM SHINE → Cost:₹4845, Suggested Sale:₹6249, Profit:₹998
-- ❌ IK 2IN1 STRAIGHT AND CURL SLIM → Cost:₹1368, Suggested Sale:₹1799, Profit:₹304
-- ❌ IK CURLING TONG CT16 → Cost:₹2536, Suggested Sale:₹3299, Profit:₹542
-- ❌ IK CURLING TONG CT22 → Cost:₹2536, Suggested Sale:₹3299, Profit:₹542
-- ❌ RICA BRAZILIAN WAX 800ML → Cost:₹1085, Suggested Sale:₹1549, Profit:₹359
-- ❌ RICA WHITE CHOCOLATE REFILL 100ML → Cost:₹190, Suggested Sale:₹299, Profit:₹76
-- ❌ RAAGA STEMCELLS PLATINUM 61G → Cost:₹348, Suggested Sale:₹499, Profit:₹105
-- ❌ FLORACTIVE W ONE CONDITIONER 300ML → Cost:₹936, Suggested Sale:₹1249, Profit:₹220
-- ❌ FLORACTIVE W ONE TREATMENT 120ML → Cost:₹1980, Suggested Sale:₹2599, Profit:₹443
-- ❌ VITAMINO COLOR MASQUE 250ML → Cost:₹634, Suggested Sale:₹849, Profit:₹147
-- ❌ OPTI CARE CONDITIONER 980GM → Cost:₹1264, Suggested Sale:₹1599, Profit:₹216
-- ❌ PLIX GUAVA COMBO 3 PACK → Cost:₹549, Suggested Sale:₹799, Profit:₹188
-- ❌ PLIX JAMUN ACNE CONTROL COMBO 2 PACK → Cost:₹357, Suggested Sale:₹549, Profit:₹145
-- ❌ PLIX PINEAPPLE COMBO 2 PACK → Cost:₹384, Suggested Sale:₹549, Profit:₹116
-- ❌ PLIX PINEAPPLE DEPIGMENT KIT → Cost:₹659, Suggested Sale:₹949, Profit:₹219
-- ❌ IK SLIM TITANIUM CRIMPER → Cost:₹3990, Suggested Sale:₹5149, Profit:₹822
-- ❌ DK CICA CALMING SUNSCREEN SPF50 80GM → Cost:₹327, Suggested Sale:₹499, Profit:₹128
-- ❌ DK WATERMELON SUNSCREEN 80GM → Cost:₹327, Suggested Sale:₹499, Profit:₹128
-- ❌ DK BLUEBERRY SUNSCREEN SPF50 80GM → Cost:₹327, Suggested Sale:₹499, Profit:₹128
-- ❌ FYC KOREAN GLASS BLEACH 270GM → Cost:₹259, Suggested Sale:₹399, Profit:₹101
-- ❌ FYC HYDRABOOST BLEACH 270GM → Cost:₹259, Suggested Sale:₹399, Profit:₹101
-- ❌ PLIX ACV TABLET 4 PACK → Cost:₹660, Suggested Sale:₹949, Profit:₹218
-- ❌ PLIX GUAVA DEWY SUNSCREEN 50G → Cost:₹250, Suggested Sale:₹399, Profit:₹111
-- ❌ PLIX JAMUN ACNE SMOOTHIE MOISTURIZER 50G → Cost:₹238, Suggested Sale:₹349, Profit:₹74
-- ❌ PILGRIM HYDRA GLOW MOISTURIZER 50G → Cost:₹151, Suggested Sale:₹249, Profit:₹68
-- ❌ PILGRIM HYDRA GLOW MOISTURIZER 100G → Cost:₹217, Suggested Sale:₹349, Profit:₹96
-- ❌ PILGRIM YOUTH GLOW MOISTURIZER 50GM → Cost:₹302, Suggested Sale:₹449, Profit:₹104
-- ❌ MN SUNSCREEN SPF60 → Cost:₹395, Suggested Sale:₹598, Profit:₹153
-- ❌ MINIMALIST MARULA OIL 50G → Cost:₹197, Suggested Sale:₹298, Profit:₹67
-- ❌ MINIMALIST B12 REPAIR FACE MOISTURIZER → Cost:₹263, Suggested Sale:₹398, Profit:₹96
-- ❌ FX GOLDEN HOUR GLOW SPF → Cost:₹192, Suggested Sale:₹299, Profit:₹74
-- ❌ FOXTALE DEWY SPF 70 50ML → Cost:₹272, Suggested Sale:₹399, Profit:₹87
-- ❌ FOXTALE MATTIFYING SPF 70 50ML → Cost:₹272, Suggested Sale:₹399, Profit:₹87
-- ❌ FOXTALE SUPER GLOW MOISTURIZER 50ML → Cost:₹272, Suggested Sale:₹399, Profit:₹87
-- ❌ FOXTALE PEARFECTION MOISTURIZER 50ML → Cost:₹245, Suggested Sale:₹399, Profit:₹117
-- ❌ FOXTALE OIL CONTROL SPF50 50G → Cost:₹219, Suggested Sale:₹349, Profit:₹94
-- ❌ DK TINTED SUNSCREEN SPF50 50ML → Cost:₹302, Suggested Sale:₹449, Profit:₹105
-- ❌ DERMA CO HYALURONIC LONG LASTING SPF 50G → Cost:₹357, Suggested Sale:₹549, Profit:₹145
-- ❌ O3+ GOLD FACIAL → Cost:₹422, Suggested Sale:₹649, Profit:₹175
-- ❌ O3+ AGEING SINGLE KIT → Cost:₹422, Suggested Sale:₹649, Profit:₹175
-- ❌ RAAGA D-TAN 72GM → Cost:₹221, Suggested Sale:₹349, Profit:₹93
-- ❌ PILGRIM ADVANCE GLOW MOISTURISER → Cost:₹302, Suggested Sale:₹449, Profit:₹104
-- ❌ FOXTALE SKIN RADIANCE MASK 75G → Cost:₹300, Suggested Sale:₹449, Profit:₹107
-- ❌ CETAPHIL GENTLE SKIN CLEANSER 250ML → Cost:₹479, Suggested Sale:₹699, Profit:₹163
-- ❌ CETAPHIL OILY SKIN CLEANSER 250ML → Cost:₹689, Suggested Sale:₹999, Profit:₹236
-- ❌ CETAPHIL BABY DAILY LOTION → Cost:₹599, Suggested Sale:₹849, Profit:₹184
-- ❌ CETAPHIL BRIGHTENING DAY CREAM SPF15 → Cost:₹779, Suggested Sale:₹1099, Profit:₹239
-- ❌ ABSOLUT REPAIR SHAMPOO 1.5L → Cost:₹1788, Suggested Sale:₹2349, Profit:₹399
-- ❌ STREAX GOLD SERUM 90ML → Cost:₹177, Suggested Sale:₹259, Profit:₹50
-- ❌ STREAX CANVO SERUM 100ML → Cost:₹252, Suggested Sale:₹399, Profit:₹109
-- ❌ ABSOLUT REPAIR MASK 490GM → Cost:₹1204, Suggested Sale:₹1599, Profit:₹280
-- ❌ MINIMALIST SALICYLIC ACID 2% FACE SERUM 30ML → Cost:₹362, Suggested Sale:₹548, Profit:₹139
-- ❌ DERMA CO 5% NIACINAMIDE FACE SERUM 30ML → Cost:₹274, Suggested Sale:₹399, Profit:₹85
-- ❌ DERMA CO SALICINAMIDE FACE SERUM 30ML → Cost:₹329, Suggested Sale:₹499, Profit:₹125
-- ❌ MINIMALIST NIACINAMIDE 5% FACE SERUM 30ML → Cost:₹395, Suggested Sale:₹598, Profit:₹153
-- ❌ XTENSO CARE SHAMPOO 1500ML → Cost:₹1788, Suggested Sale:₹2349, Profit:₹399
-- ❌ BIO SMOOTH THERA SHAMPOO 1000ML → Cost:₹948, Suggested Sale:₹1199, Profit:₹157
-- ❌ BIO COLORLAST SHAMPOO 1000ML → Cost:₹948, Suggested Sale:₹1199, Profit:₹157
-- ❌ OPTI CARE SHAMPOO 1000ML → Cost:₹1086, Suggested Sale:₹1374, Profit:₹183
-- ❌ PILGRIM HAIRFALL CONTROL SHAMPOO 200ML → Cost:₹190, Suggested Sale:₹299, Profit:₹76
-- ❌ DERMA CO 2% SALICYLIC ACID FACE SERUM 30ML → Cost:₹274, Suggested Sale:₹399, Profit:₹85
-- ❌ STREAX CANVO SHAMPOO 1500ML → Cost:₹868, Suggested Sale:₹1149, Profit:₹194
-- ❌ STREAX CANVOLINE SHAMPOO 300ML → Cost:₹304, Suggested Sale:₹449, Profit:₹103
-- ❌ CURL SHAMPOO 300ML → Cost:₹845, Suggested Sale:₹1149, Profit:₹219
-- ❌ INFORCER SHAMPOO 300ML → Cost:₹509, Suggested Sale:₹699, Profit:₹132
-- ❌ SCALP ADVANCED SHAMPOO 300ML → Cost:₹563, Suggested Sale:₹799, Profit:₹173
-- ❌ METAL DX MASK 250ML → Cost:₹1024, Suggested Sale:₹1349, Profit:₹225
-- ❌ SCALP OIL SHAMPOO 300ML → Cost:₹717, Suggested Sale:₹949, Profit:₹157
-- ❌ FLORACTIVE W ONE SHAMPOO 300ML → Cost:₹936, Suggested Sale:₹1249, Profit:₹220
-- ❌ DENSITY ADV SHAMPOO 300ML → Cost:₹448, Suggested Sale:₹649, Profit:₹147
-- ❌ SILVER SHAMPOO 300ML → Cost:₹509, Suggested Sale:₹699, Profit:₹132
-- ❌ LISS UNLIMITED SHAMPOO 300ML → Cost:₹509, Suggested Sale:₹699, Profit:₹132
-- ❌ VITAMINO COLOR SHAMPOO 300ML → Cost:₹509, Suggested Sale:₹699, Profit:₹132
-- ❌ VITAMINO SPECTRUM SHAMPOO 300ML → Cost:₹890, Suggested Sale:₹1199, Profit:₹220
-- ❌ STREAX CANVO SHAMPOO 500ML → Cost:₹384, Suggested Sale:₹549, Profit:₹116
-- ❌ PILGRIM DAMAGE REPAIR SHAMPOO 200ML → Cost:₹168, Suggested Sale:₹249, Profit:₹50
-- ❌ O3+ DTAN SINGLE FACIAL KIT → Cost:₹422, Suggested Sale:₹649, Profit:₹175
-- ❌ O3+ VITAMIN SINGLE FACIAL KIT → Cost:₹422, Suggested Sale:₹649, Profit:₹175
-- ❌ PILGRIM SMOOTHENING SHAMPOO 200ML → Cost:₹190, Suggested Sale:₹299, Profit:₹76
-- ❌ LISS UNLIMITED SHAMPOO 1500ML → Cost:₹1716, Suggested Sale:₹2249, Profit:₹378
-- ❌ LISS UNLIMITED MASK 250ML → Cost:₹639, Suggested Sale:₹849, Profit:₹140
-- ❌ WP FUSION SHAMPOO 250ML → Cost:₹554, Suggested Sale:₹749, Profit:₹133
-- ❌ WP ELEMENT SHAMPOO 250ML → Cost:₹577, Suggested Sale:₹799, Profit:₹158
-- ❌ CURL HAIR MASK 250ML → Cost:₹1024, Suggested Sale:₹1349, Profit:₹225
-- ❌ INFORCER MASK 250ML → Cost:₹639, Suggested Sale:₹849, Profit:₹140
-- ❌ SCALP ADVANCED MASK 250ML → Cost:₹800, Suggested Sale:₹1099, Profit:₹217
-- ❌ VITAMINO SPECTRUM MASK 250ML → Cost:₹1056, Suggested Sale:₹1399, Profit:₹241
-- ❌ PLIX JAMUN MARKS TREATMENT SERUM 30ML → Cost:₹288, Suggested Sale:₹449, Profit:₹120
-- ❌ MATRIX SOCOLOR 5.0 90GM → Cost:₹328, Suggested Sale:₹414, Profit:₹42
-- ❌ MATRIX SOCOLOR 4.0 90GM → Cost:₹328, Suggested Sale:₹414, Profit:₹42
-- ❌ LUXLISS DAILY CARE SHAMPOO 250ML → Cost:₹648, Suggested Sale:₹899, Profit:₹182
-- ❌ PILGRIM DAMAGE REPAIR CONDITIONER 200ML → Cost:₹217, Suggested Sale:₹349, Profit:₹96
-- ❌ MINIMALIST VITAMIN C 10 FACE SERUM → Cost:₹461, Suggested Sale:₹649, Profit:₹133
-- ❌ DK 10% VITAMIN C SUPER FACE SERUM → Cost:₹382, Suggested Sale:₹549, Profit:₹118
-- ❌ PILGRIM 24K GOLD GEL FACE WASH 80ML → Cost:₹217, Suggested Sale:₹349, Profit:₹96
-- ❌ PLIX PINEAPPLE 2% DEWY SERUM 30ML → Cost:₹316, Suggested Sale:₹449, Profit:₹89
-- ❌ CETAPHIL MOISTURISING LOTION 250ML → Cost:₹779, Suggested Sale:₹1099, Profit:₹239
-- ❌ PILGRIM SMOOTHENING CONDITIONER 200ML → Cost:₹220, Suggested Sale:₹349, Profit:₹93
-- ❌ IK HAIR DRYER BLAZE → Cost:₹1682, Suggested Sale:₹2199, Profit:₹365
-- ❌ BERINA HAIR MOUSSE 300ML → Cost:₹307, Suggested Sale:₹449, Profit:₹100
-- ❌ STREAX CANVOLIEN CONDITIONER 240G → Cost:₹290, Suggested Sale:₹399, Profit:₹68
-- ❌ EXCELLENCE COLOUR 3 → Cost:₹492, Suggested Sale:₹699, Profit:₹149
-- ❌ O3+ MELADERM VITAMIN C GEL BLEACH → Cost:₹515, Suggested Sale:₹749, Profit:₹175
-- ❌ XTENSO SERUM 50ML → Cost:₹509, Suggested Sale:₹749, Profit:₹182
-- ❌ IK HAIR STRAIGHTENER S3 → Cost:₹2992, Suggested Sale:₹3949, Profit:₹699
-- ❌ IK HAIR DRYER 2000 → Cost:₹1710, Suggested Sale:₹2249, Profit:₹384
-- ❌ DK VITAMIN C SUNSCREEN SPF50 80GM → Cost:₹327, Suggested Sale:₹499, Profit:₹128
-- ❌ FYC VITAMIN C BLEACH 270GM → Cost:₹259, Suggested Sale:₹399, Profit:₹101
-- ❌ O3+ BRIDAL VITAMIN C KIT → Cost:₹504, Suggested Sale:₹749, Profit:₹186
-- ❌ DERMA CO 2% KOJIC ACID FACE SERUM 10ML → Cost:₹164, Suggested Sale:₹249, Profit:₹53
-- ❌ DERMA CO 5% VITAMIN C MOISTURISER → Cost:₹192, Suggested Sale:₹299, Profit:₹74
-- ❌ BERINA HAIR PROTECTOR 230ML → Cost:₹543, Suggested Sale:₹749, Profit:₹144
-- ❌ BERINA HAIR SPA CREAM 100GM → Cost:₹185, Suggested Sale:₹298, Profit:₹80
-- ❌ PILGRIM VITAMIN C MOISTURISER 50G → Cost:₹190, Suggested Sale:₹299, Profit:₹76