"""
generate-price-sql.py
Reads price-fixes.json + Supabase products via API, matches by name keywords,
generates SQL UPDATE statements for profitable prices.
"""
import json, re, math, urllib.request, os

def normalize(s):
    return re.sub(r'[^a-z0-9]', ' ', s.lower()).strip()

def match_score(inv_name, db_name):
    inv_words = set(normalize(inv_name).split()) - {'ml','gm','g','l','no','of','and','in','for',
                                                      'the','a','an','with','pack','combo','care'}
    db_words  = set(normalize(db_name).split())  - {'ml','gm','g','l','no','of','and','in','for',
                                                      'the','a','an','with','pack','combo','care'}
    if len(inv_words) < 2 or len(db_words) < 2: return 0
    overlap = inv_words & db_words
    score = len(overlap) / max(len(inv_words), len(db_words)) * 100
    return score

# Load calculated prices
with open('scripts/price-fixes.json') as f:
    fixes = json.load(f)

# Fetch products from Supabase REST API
SUPA_URL = "https://aukylplgvwreaovrfher.supabase.co"
SUPA_KEY  = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1a3lscGxndndyZWFvdnJmaGVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQwNDY2ODEsImV4cCI6MjA5OTYyMjY4MX0.ezalumzz6wxFDWOJQHgnMjx_v5xjoM3oWq8vmmn-SBo"

req = urllib.request.Request(
    f"{SUPA_URL}/rest/v1/products?select=id,name,brand,price,mrp&limit=500",
    headers={"apikey": SUPA_KEY, "Authorization": f"Bearer {SUPA_KEY}"}
)
with urllib.request.urlopen(req) as r:
    db_products = json.loads(r.read())

print(f"Loaded {len(db_products)} products from DB")
print(f"Loaded {len(fixes)} price fixes from invoice")
print()

sql_lines = ["-- Auto-generated price updates from invoice analysis",
             "-- Formula: Cost + 8% delivery + ₹18 packaging + category margin",
             "-- Generated by scripts/generate-price-sql.py",
             "-- Run in Supabase SQL editor\n",
             "-- First add cost_price column if not exists:",
             "ALTER TABLE products ADD COLUMN IF NOT EXISTS cost_price NUMERIC(10,2);\n"]

matches = []
no_match = []

for fix in fixes:
    best_score = 0
    best_db = None
    for db in db_products:
        score = match_score(fix['name'], db['name'])
        if score > best_score:
            best_score = score
            best_db = db
    if best_score >= 25 and best_db:
        matches.append((fix, best_db, best_score))
    else:
        no_match.append(fix)

# Sort by confidence descending
matches.sort(key=lambda x: x[2], reverse=True)

# ── CRITICAL: deduplicate — each DB product gets only the BEST match ──────
seen_ids = {}
deduped = []
for (fix, db, score) in matches:
    if db['id'] not in seen_ids:
        seen_ids[db['id']] = True
        deduped.append((fix, db, score))
    else:
        no_match.append(fix)
matches = deduped

print(f"✅ Matched: {len(matches)} products")
print(f"❌ No match: {len(no_match)} products")
print()

sql_lines.append("-- ═══════════════════════════════════════════════════════")
sql_lines.append("-- PRICE UPDATES (matched by name similarity ≥35%)")
sql_lines.append("-- ═══════════════════════════════════════════════════════\n")

total_profit = 0
for (fix, db, score) in matches:
    old_price = db['price']
    new_price = fix['sale_price']
    new_mrp   = fix['mrp']
    cost      = fix['cost']
    profit    = fix['profit']
    margin    = fix['margin_pct']
    disc_pct  = fix['discount_pct']
    total_profit += profit

    change = "↑" if new_price > old_price else ("↓" if new_price < old_price else "=")
    sql_lines.append(f"-- {fix['name'][:55]}")
    sql_lines.append(f"-- Cost:₹{cost:.0f} → Sale:₹{new_price} (was ₹{old_price}) | Profit:₹{profit:.0f} ({margin}%) | {disc_pct}% OFF MRP | Match:{score:.0f}% {change}")
    sql_lines.append(f"UPDATE products SET")
    sql_lines.append(f"  price = {new_price},")
    sql_lines.append(f"  mrp = {new_mrp},")
    sql_lines.append(f"  discount = {disc_pct},")
    sql_lines.append(f"  cost_price = {cost}")
    sql_lines.append(f"WHERE id = '{db['id']}';")
    sql_lines.append("")

sql_lines.append(f"\n-- ═══════════════════════════════════════════════════════")
sql_lines.append(f"-- SUMMARY: {len(matches)} products updated")
sql_lines.append(f"-- Expected total profit per sell-through: ₹{total_profit:.0f}")
sql_lines.append(f"-- Average margin: ~{total_profit / sum(f['cost'] for f,_,_ in matches) * 100:.1f}%")
sql_lines.append(f"-- ═══════════════════════════════════════════════════════")

if no_match:
    sql_lines.append("\n-- UNMATCHED PRODUCTS (set manually in Price Manager):")
    for fix in no_match:
        sql_lines.append(f"-- ❌ {fix['name']} → Cost:₹{fix['cost']:.0f}, Suggested Sale:₹{fix['sale_price']}, Profit:₹{fix['profit']:.0f}")

sql_text = "\n".join(sql_lines)
with open('supabase-price-updates.sql', 'w', encoding='utf-8') as f:
    f.write(sql_text)

print(f"✅ SQL written to supabase-price-updates.sql")
print(f"   {len(matches)} products matched and priced")
print(f"   Expected profit per sell-through: ₹{total_profit:.0f}")
print()
print("TOP 10 MATCHES:")
for (fix, db, score) in matches[:10]:
    print(f"  {score:.0f}% | {fix['name'][:40]:<40} → DB: {db['name'][:40]}")
print()
print("BIGGEST PRICE CHANGES:")
changes = [(fix['sale_price'] - db['price'], fix, db) for fix,db,_ in matches]
changes.sort(key=lambda x: abs(x[0]), reverse=True)
for (diff, fix, db) in changes[:10]:
    arrow = "↑" if diff > 0 else "↓"
    print(f"  {arrow} Rs.{abs(int(diff)):4d} | {db['name'][:45]:<45} | Rs.{db['price']} -> Rs.{fix['sale_price']}")
